### ISSUE TITLE
gui causes segmentation fault

### ISSUE THREAD

**Issue by EphTron** [vrsys/guacamole#134]
Running an application with multiple avango.gua.gui.nodes.GuiResource() more than once causes segmentation faults.
Whenever I run my app it only works one time. After closing it in the console with ctrl+c and starting it again it crashes with a segmentation fault. Changing something in the code fixes the bug for one more run, then I get the same error again. 
Sometimes it even crashes on the first run.
To me it seems like something is not destructed the right way.
I am using different names for every GuiResource.

**Comment by Simmesimme** [comment]
fixed in 2154854
