### ISSUE TITLE
Reaching uniform limitation for more complex scenes

### ISSUE THREAD

**Issue by scholli** [vrsys/guacamole#61]
In UniformMapping::add() uniforms of same type are currently pushed into static array.
For >500 materials (e.g. in medieval harbour) these arrays become too large! Shader compilation fails.
As a solution use a UBO or samplerBuffer instead!

**Comment by thelaui** [comment]
This shouldn't be an issue with the current rendering approach as uniforms are set for each rendered geometry individually.
